functionality:
  name: fastqc
  namespace: template
  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
      example: "file.fastq.gz"
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      required: true
      direction: output
      example: "fastqc_output_dir/"
  resources:
    - type: bash_script
      path: script.sh
platforms:
  - type: docker
    image: registry.ardigen.com/if-pan/dockers/qc:latest
  - type: nextflow
  - type: native
